hv-rhel5.x/hv/tools/hv_fcopy_daemon.c

This bug has only been observed on RHEL 5.X. When the file offset exceeds 2GB, our daemon calls into pwrite with the right value; but the pwrite wrapper logic corrupts this offset prior to passing it to the pwrite64 call.

Fcopy should call pwrite64 directly.

---

hv-rhel6.x/hv/channel_mgmt.c

Reverts LIS/lis-next#25
Reverting this change since it was a hack to improve perf for 4.0.11 , will commit changes now from upstream,

Revert "Fix netvsc performance regression bug for rhel6.x"

---

diffs/LIS4.0/rhel7x_rhel6x.patch
hv-rhel6.x/hv/Makefile
hv-rhel6.x/hv/hv_kvp.c
hv-rhel6.x/hv/include/linux/hv_compat.h
hv-rhel6.x/hv/overrides.mk
hv-rhel6.x/hv/rndis_filter.c
hv-rhel6.x/hv/storvsc_drv.c
hv-rhel7.x/hv/CHANGELOG
hv-rhel7.x/hv/Makefile
hv-rhel7.x/hv/overrides.mk
hv-rhel7.x/hv/storvsc_drv.c

- Backport storvsc SRB flag patches from linux-next
- Introduce version macros for building against update kernels (build was broken on 6.4 update kernels due to ABI changes in utf8s_to_utf16s function)
- Overrides.mk no longer needed, as include path can be specified directly within Makefile

SRB Backports and build break fixes

---

hv-rhel7.x/hv/netvsc_drv.c

This reverts commit b64f20f831e3c454588349500fba571add6e0fcf.
In RHEL7.1 + kernel, it does provided function of skb_get_hash(). But it is still too old compared with the current upstream skb_get_hash() code.
The skb_get_hash() provided by RHEL7.1 kernel did not include UDP port so it will not help the UDP RSS processing.

Revert "Use upstream Jenkins hash for RSS hashing in rhel7.x driver"

---

hv-rhel6.x/hv/provider.c
hv-rhel7.x/hv/provider.c

[hv-rhel6.x/hv/provider.c:827] -> [hv-rhel6.x/hv/provider.c:830]: (warning) Either the condition 'attr!=0' is redundant or there is possible null pointer dereference: attr.
[hv-rhel6.x/hv/provider.c:828] -> [hv-rhel6.x/hv/provider.c:830]: (warning) Either the condition 'attr!=0' is redundant or there is possible null pointer dereference: attr.
[hv-rhel7.x/hv/provider.c:846] -> [hv-rhel7.x/hv/provider.c:849]: (warning) Either the condition 'attr!=0' is redundant or there is possible null pointer dereference: attr.
[hv-rhel7.x/hv/provider.c:847] -> [hv-rhel7.x/hv/provider.c:849]: (warning) Either the condition 'attr!=0' is redundant or there is possible null pointer dereference: attr.

cppcheck issues

---

hv-rhel5.x/hv/storvsc_drv.c

This reverts commit 8fa3a2c1ed4256d9779cb32557dc4a03fdb497b1.
This was causing a build break on RH5.X

Revert "RH5: storvsc: set the block max size to VSP reported value"

---

hv-rhel6.x/hv/netvsc_drv.c

In the 32 bits of CentOS 6.7, the skb structure for DHCP Discovery
message may have transport_header point to NULL.
In this case, udp_hdr(skb) will return NULL reference, and current
implementation of udp_hdr(skb)->source will crash the kernel when
bootup it with a NIC set to dhcp mode.
This patch will check the udp_hdr(skb) before we use it.

hv_netvsc: fix a UDP RSS hashing bug for rhel 6.x tree

---

hv-rhel6.x/hv/hyperv_net.h
hv-rhel6.x/hv/netvsc_drv.c
hv-rhel7.x/hv/hyperv_net.h
hv-rhel7.x/hv/netvsc_drv.c

This includes:
RH6: add skb_reset_transport_header() to ensure tcp_hdr() returns valid pointer.
RH6: hv_netvsc: Don't ask for additional head room in the skb.
RH7: hv_netvsc: Don't ask for additional headroom in the skb.

Merge recent master changes into 1605 branch

---

hv-rhel6.x/hv/storvsc_drv.c
hv-rhel7.x/hv/storvsc_drv.c

The revert to the 5.x tree was done on June 15.  This is for the 6.x and 7.x trees.  Tested on 7.2, 7.0, 6.8x64, 6.7x64, 6.0x32, 5.11x64, 5.8x64, 5.5x32, 5.3x32.

Merge storvsc reverts from master to 1605 branch

---

hv-rhel6.x/hv/tools/hv_kvp_daemon.c
hv-rhel7.x/hv/tools/hv_kvp_daemon.c

Update how the *-release files are processed.  The SuSE-release is multiple lines of content. The redhat-release is a single line, so the text needs to be parsed to extract the major/minor version numbers.

RH7: RH6: daemons: Update processing of *-release files

---

hv-rhel6.x/hv/Makefile
hv-rhel6.x/hv/provider.c

this one-time patch is for 4.1.3 only. The code for handling ND binding will move to notification chain in the mainline

use seperate work queue for RDMA probe

---

hv-rhel6.x/hv/include/linux/hv_compat.h
hv-rhel7.x/hv/netvsc_drv.c

Currently the UDP traffic after RSS hashed will meet high datagram loss
issues with some versions of host netvsp.
Exclude UDP port from RSS hashing in this patch.

RH6: hv_netvsc: exclude UDP ports in RSS hashing

---

hv-rhel6.x/hv/channel.c
hv-rhel6.x/hv/channel_mgmt.c
hv-rhel6.x/hv/hyperv_vmbus.h
hv-rhel6.x/hv/include/linux/hyperv.h
hv-rhel6.x/hv/ring_buffer.c

Drivers: hv: vmbus: Base host signaling strictly on the ring state
Drivers: hv: vmbus: On write cleanup the logic to interrupt the host
Drivers: hv: vmbus: On the read path cleanup the logic to interrupt the host

backport KY's patches which addressed the host side throttling

---

hv-rhel6.x/hv/include/linux/hv_compat.h

This was causing some build breaks for user-mode daemons.

RH6: Move some kernel code back under #ifdef __KERNEL

---

hv-rhel6.x/hv/hyperv_net.h
hv-rhel6.x/hv/netvsc.c
hv-rhel6.x/hv/netvsc_drv.c
hv-rhel6.x/hv/rndis_filter.c
hv-rhel7.x/hv/hyperv_net.h
hv-rhel7.x/hv/netvsc.c
hv-rhel7.x/hv/netvsc_drv.c
hv-rhel7.x/hv/rndis_filter.c

netvsc: don't pass void * to internal device_add
netvsc: simplify rndis_filter_remove

Backport two patches from LIS upstream

---

hv-rhel6.x/hv/arch/x86/hyperv/hv_init.c
hv-rhel6.x/hv/arch/x86/include/lis/asm/mshyperv.h
hv-rhel6.x/hv/hv_util.c
hv-rhel7.x/hv/arch/x86/hyperv/hv_init.c
hv-rhel7.x/hv/arch/x86/include/lis/asm/mshyperv.h
hv-rhel7.x/hv/hv_util.c

Introduce PTP-based TimeSync config in RH7. On RH6, PTP doesn't exist, so we provide a module param to enable TimeSync instead.

RH6/RH7: Fix TimeSync behavior

---

hv-rhel6.x/hv/netvsc_drv.c

Properly support and report the rx-checksumming flag on RHEL 6.x

RH6: hv: fix rx-checksumming support

---

hv-rhel7.x/hv/pci-hyperv.c

This patch uses the lower 16 bits of the serial number as PCI
domain, otherwise some drivers may not be able to handle it.
Signed-off-by: Haiyang Zhang <haiyangz@microsoft.com>

RH7: pci-hyperv: Use only 16 bit integer for PCI domain

---

hv-rhel7.x/hv/hyperv_net.h
hv-rhel7.x/hv/netvsc.c
hv-rhel7.x/hv/netvsc_drv.c
hv-rhel7.x/hv/rndis_filter.c

upstream commit ID 15a863bf7436124e799ba175a801e25f7b57191e
Use NAPI (softirq), to handle receive packets and send completions.
Previously this was handled by tasklet.
Signed-off-by: Stephen Hemminger <sthemmin@microsoft.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

RH7: netvsc: implement NAPI

---

hv-rhel6.x/hv/netvsc_drv.c
hv-rhel6.x/hv/rndis_filter.c
hv-rhel7.x/hv/netvsc_drv.c
hv-rhel7.x/hv/rndis_filter.c

netvsc: Properly initialize the return value
386f57622cc3bbb39b9c00fc8762bc9ab28e0f8d
Initialize the return value correctly.
Signed-off-by: K. Y. Srinivasan <kys@microsoft.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

netvsc: Properly initialize the return value

---

hv-rhel6.x/hv/include/linux/hyperv.h
hv-rhel6.x/hv/netvsc.c
hv-rhel6.x/hv/netvsc_drv.c
hv-rhel6.x/hv/ring_buffer.c
hv-rhel6.x/hv/rndis_filter.c
hv-rhel7.x/hv/netvsc_drv.c
hv-rhel7.x/hv/rndis_filter.c

vmbus: introduce in-place packet iterator
f3dd3f4797652c311df9c074436d420f1ad3566e
This is mostly just a refactoring of previous functions
(get_pkt_next_raw, put_pkt_raw and commit_rd_index) to make it easier
to use for other drivers and NAPI.
---
netvsc: enable GRO
742fe54c7b03c83ce8067822a8739a4091c319ed
Use GRO when receiving packets.
---
netvsc: replace netdev_alloc_skb_ip_align with napi_alloc_skb
e91e7dd71dedbf4508513c8a66212248a853ecbe
Gives potential performance gain.
---
netvsc: handle offline mtu and channel change
163891d7d42935e7499daa0646a8eb3c44504300
If device is not up, then changing MTU (or number of channels)
should not re-enable the device.

patchwork set 2 - RH7

---

hv-rhel6.x/hv/hyperv_net.h
hv-rhel6.x/hv/netvsc.c
hv-rhel6.x/hv/netvsc_drv.c
hv-rhel6.x/hv/rndis_filter.c
hv-rhel7.x/hv/hyperv_net.h
hv-rhel7.x/hv/netvsc.c

netvsc: implement NAPI
15a863bf7436124e799ba175a801e25f7b57191e
Use NAPI (softirq), to handle receive packets and send completions.
Previously this was handled by tasklet.
---
netvsc: enable GRO
742fe54c7b03c83ce8067822a8739a4091c319ed
Use GRO when receiving packets.
---
netvsc: fix NAPI performance regression
f4f1c23d6e41f5ee4973a6da65cba1e1c536ec29
When using NAPI, the single stream performance declined signifcantly
because the poll routine was updating host after every burst
of packets. This excess signalling caused host throttling.
This fix restores the old behavior. Host is only signalled
after the ring has been emptied.

patchwork set 3

---

hv-rhel7.x/hv/include/linux/hv_compat.h
hv-rhel7.x/hv/netvsc.c

netvsc: use napi_consume_skb
f9645430ef5f53ddf0ddd481e9f70f6fce7ccff2
This allows using deferred skb freeing and with NAPI. And get buffer
recycling.

RH7: netvsc: use napi_consume_skb

---

hv-rhel6.x/hv/channel_mgmt.c
hv-rhel6.x/hv/hyperv_net.h
hv-rhel6.x/hv/include/linux/hv_compat.h
hv-rhel6.x/hv/include/linux/hyperv.h
hv-rhel6.x/hv/netvsc.c
hv-rhel6.x/hv/netvsc_drv.c
hv-rhel6.x/hv/vmbus_drv.c

Masked functions that are present only in RHEL 6.4 and reverted commits that cannot be ported on older versions (<6.4).

RH6: RCU commits cleanup

---

hv-rhel7.x/hv/hyperv_net.h
hv-rhel7.x/hv/netvsc_drv.c

hv_netvsc: Fix the queue index computation in forwarding case
8db91f6a9b2ff2bb5355ad11c668fe63eb8ae0c3
If the outgoing skb has a RX queue mapping available, we use the queue
number directly, other than put it through Send Indirection Table.

RH7: hv_netvsc: Fix the queue index computation in forwarding case

---

hv-rhel7.x/hv/arch/x86/include/uapi/lis/asm/hyperv.h
hv-rhel7.x/hv/pci-hyperv.c

This updates the backporting that was started in commit:
fe4bfc622be20380da0da02c81568a582304a512

RH7: Add some missing backports that were missed in last PCI patch

---

hv-rhel7.x/hv/rhel7-hv-driver-install

In 4.2.0 and 4.2.1 branches, the Mellanox module is included in the mlx4 folder, however it is not installed because it is omitted in the copy command.

RH7: Update rhel7-hv-driver-install to include mlx module install

---

hv-rhel6.x/hv/storvsc_drv.c
hv-rhel7.x/hv/storvsc_drv.c

scsi: storvsc: remove return at end of void function
8d4208c1a73ab30e05da142e0f05b2b02fc26fc9
storvsc_on_channel_callback is a void function and the return
statement at the end is not useful.
Found with checkpatch.
---
scsi: storvsc: Prefer kcalloc over kzalloc with multiply
e04085285b829dc922e78768a9abb390a8caed31
Use kcalloc for allocating an array instead of kzalloc with multiply,
kcalloc is the preferred API.
Found with checkpatch.

RH6 & RH7 storvsc upstream commits

---

hv-rhel6.x/hv/netvsc_drv.c

author: Simon Xiao <sixiao@microsoft.com>
commit f3c9d40ee12926f330a1dfebce0bebadd1406ba6
The netvsc device supports full duplex by default.
This warnings in log from bonding device which did not like
seeing UNKNOWN duplex.

[hv-rhel6.x] hv_netvsc: change netvsc device default duplex to FULL

---

hv-rhel6.x/hv/tools/hv_vss_daemon.c
hv-rhel7.x/hv/tools/hv_vss_daemon.c

6113e3d28149dee33f10e92df6a16efb2b9cf473
If a FREEZE operation takes too long, the driver may time out and move
on
to another  operation. The daemon is unaware of this and attempts to
notify the driver that the FREEZE succeeded. This results in an error
from
the driver and the daemon leaves the filesystem in frozen state.
Fix this by thawing the filesystem and continuing.

Tools: hv: vss: Thaw the filesystem and continue if freeze call has timed out

---

hv-rhel6.x/hv/hyperv_vmbus.h
hv-rhel7.x/hv/hyperv_vmbus.h

1e052a16eb2caf6727b594cad0744ccdfddf4254
The current code unconditionally sends an IPI. If we are running on the
correct CPU and are in interrupt level, we don't need an IPI.
Make this adjustment.

Drivers: hv: util: Make hv_poll_channel() a little more efficient

---

hv-rhel6.x/hv/channel_mgmt.c
hv-rhel6.x/hv/hv.c
hv-rhel6.x/hv/hyperv_vmbus.h
hv-rhel6.x/hv/vmbus_drv.c
hv-rhel7.x/hv/arch/x86/include/lis/asm/mshyperv.h
hv-rhel7.x/hv/channel.c
hv-rhel7.x/hv/channel_mgmt.c
hv-rhel7.x/hv/connection.c
hv-rhel7.x/hv/hv.c
hv-rhel7.x/hv/hyperv_vmbus.h
hv-rhel7.x/hv/vmbus_drv.c

e6242fa0fb50570acb6364446dec369d7b9b5b2c
This table is immutable and should be const.
Cleanup indentation and whitespace for this as well.
---
e546d778d6bb3e1a80697a6556d870c707e6df82
The current code uses the MSR based mechanism to get the current tick.
Use the current clock source as that might be more optimal.
---
13b9abfc92be7c4454bff912021b9f835dea6e15
Extend the disabling of preemption to include the hypercall so that
another thread can't get the CPU and corrupt the per-cpu page used
for hypercall arguments.
---
54a66265d6754b37fb4baf1d970ec88a6225a988
Fix the rescind handling. This patch addresses the following rescind
scenario that is currently not handled correctly:
If a rescind were to be received while the offer is still being
peocessed, we will be blocked indefinitely since …

RH6  & RH7: upstream patch-work set May 2017

---

hv-rhel7.x/hv/hv.c

Commit "hv: change clockevents unbind tactics" prepares for CPU offlining support.
Code is breaking kdump functionality, thus we have to revert the code for LIS.

Partial revert for hv: change clockevents unbind tactics

---

hv-rhel5.x/hv/tools/hv_vss_daemon.c
hv-rhel6.x/hv/tools/hv_vss_daemon.c
hv-rhel7.x/hv/tools/hv_vss_daemon.c

The hypervvssd daemon freezes loop devices. This results in deadlocks if the thawing doesn't occur in the reverse order and the loop backed filesystem is thawed before the filesystem that contains the backing file.
This is especially evident in cPanel VMs as cPanel setups loop devices on its own.
This commit skips over loop-backed filesystems. I decided upon this as this is whats VMware says it did with open-vm-tools (https://github.com/vmware/open-vm-tools/issues/6).
If needed I could also supply a patch that stores the freeze order and replays it in reverse for thawing. (That would be a more error-prone commit than this one though.)
**NOTE**: Tested on CentOS7.3 **only** (_should work equally well with other versions though as the changes are minimal_).

RHEL5,6,7 VSS - Skip freezing filesystems backed by loop devices.

---

hv-rhel6.x/hv/channel.c
hv-rhel6.x/hv/connection.c
hv-rhel6.x/hv/hv_balloon.c
hv-rhel6.x/hv/hv_fcopy.c
hv-rhel6.x/hv/hv_kvp.c
hv-rhel6.x/hv/hv_snapshot.c
hv-rhel6.x/hv/hv_utils_transport.c
hv-rhel6.x/hv/hv_utils_transport.h
hv-rhel6.x/hv/hyperv_vmbus.h
hv-rhel6.x/hv/include/linux/hyperv.h
hv-rhel6.x/hv/netvsc.c
hv-rhel6.x/hv/ring_buffer.c
hv-rhel6.x/hv/rndis_filter.c
hv-rhel6.x/hv/vmbus_drv.c
hv-rhel7.x/hv/channel.c
hv-rhel7.x/hv/connection.c
hv-rhel7.x/hv/hv.c
hv-rhel7.x/hv/hv_balloon.c
hv-rhel7.x/hv/hv_fcopy.c
hv-rhel7.x/hv/hv_kvp.c
hv-rhel7.x/hv/hv_snapshot.c
hv-rhel7.x/hv/hv_utils_transport.c
hv-rhel7.x/hv/hv_utils_transport.h
hv-rhel7.x/hv/hyperv_vmbus.h
hv-rhel7.x/hv/include/linux/hyperv.h
hv-rhel7.x/hv/netvsc.c
hv-rhel7.x/hv/ring_buffer.c
hv-rhel7.x/hv/rndis_filter.c
hv-rhel7.x/hv/vmbus_drv.c

2be0f2644598ee4b8ea0ed6a32913e1ce0212c9c
This fixes a race where vmbus callback for new packet arriving
could occur before NAPI is initialized.
---
4827ee1dca5691c9fc568883170a568db94f9b38
Allow driver to get debug information about state of the ring.

RH6 & RH7: upstream patch-work set 2

---

hv-rhel5.x/hv/vmbus_drv.c

VMbus device names had format "vmbus_0_%d" in LIS 3.5, but were changed in LIS 4.0 and later to be "vmbus_%d".  This change broke 'kudzu' in RHEL/CentOS 5.x which has specific code for parsing the "_0".  So changing this back to the original format.  Change is made in the RHEL/CentOS 5.x branch only because 'kudzu' is not used in RHEL/CentOS 6.x and 7.x.

Add "_0" back into vmbus device name

---

hv-rhel6.x/hv/tools/hv_kvp_daemon.c
hv-rhel7.x/hv/hv_util.c
hv-rhel7.x/hv/tools/hv_kvp_daemon.c

tools: hv: properly handle long paths
a1a7ea6bd6d55b6620c9c0a43bf684d6c427172a
Paths can be up to PATH_MAX long and PATH_MAX is usually greater than
256.
While on it, simplify path reconstruction to a simple snprintf(), define
and reuse KVP_NET_DIR.
---
only RH7: hv_utils: drop .getcrosststamp() support from PTP driver
4f9bac039a64f6306b613a0d90e6b7e75d7ab0c4

RH6 & RH7: upstream patch-work set May 2017

---

hv-rhel6.x/hv/hyperv_net.h
hv-rhel7.x/hv/hyperv_net.h

2d05b56097664e1d8b7fd690e6eac03cc6a82cc3
The element netvsc_device:extension is always a pointer to RNDIS
information.

netvsc: use typed pointer for internal state

---

tools/sriov/60-hyperv-sriov.rules
tools/sriov/bondvf_lock
tools/sriov/hv_vf_name

60-hyperv-sriov.rules: name the VF device in udev rule;
hv_vf_name: get the VF PCI ID;
bondvf_lock: a wrapper of bondvf.sh with file lock support.

[SRIOV] check in the SRIOV config files

---

hv-rhel7.x/hv/vmbus_drv.c

This fixes commit 67c89f4c2120d52a39c654d96aff6b57ae707bad.
RH7: Drivers: hv: vmbus: Fix rescind handling

RH7: Make sure to release channel lock during rescind.

---

hv-rhel6.x/hv/hyperv_net.h
hv-rhel6.x/hv/rndis_filter.c
hv-rhel7.x/hv/hyperv_net.h
hv-rhel7.x/hv/netvsc.c
hv-rhel7.x/hv/netvsc_drv.c
hv-rhel7.x/hv/rndis_filter.c

53fa1a6f33520f01f9dbee48369074b34d77616b
When the VF NIC is opened, the synthetic NIC's carrier state is set to
off. This tells the host to transitions data path to the VF device. But
if startup script or user manipulates the admin state of the netvsc
device directly for example:
Then the carrier state of the synthetic NIC would be on, even though the
data path was still over the VF NIC. This patch sets the carrier state
of synthetic NIC with consideration of the related VF state.
---
dedb459e13f05824bc33d2d861e9b576bfc8d0bb
We simply use rndis_device->link_state in the netdev_dbg. The variable,
link_state from struct netvsc_device_info, is not used anywhere else.

RH7 & RH6: netvsc June 23rd upstream

---

hv-rhel5.x/hv/vmbus_drv.c

Remove the 4th dash from device_id and class_id GUIDs so the string format matches the LIS that is built-in RHEL/Cent/OS 5.x releases and matches what kudzu expects.  Kudzu is doing string compares to find the class_id, and the extra dash when LIS is installed causes the compares to fail, which in turn causes the network to not be configured when rebooting after installing LIS.

Remove 4th dash from device_id and class_id GUIDs

---

hv-rhel6.x/hv/vmbus_drv.c

This fixes an issue introduced by backport commit:
f3ad7fdb1e2129c23092ca7d2a9a9f1c6cfb6d83

RH6: Avoid scheduling rescind work on global workqueue.

---

hv-rhel7.x/hv/include/linux/hyperv.h
hv-rhel7.x/hv/ring_buffer.c

Contains:
vmbus: add prefetch to ring buffer iterator
vmbus: more host signalling avoidance
vmbus: eliminate duplicate cached index
vmbus: refactor hv_signal_on_read
vmbus: drop unused ring_buffer_info elements
vmbus: simplify hv_ringbuffer_read

vmbus upstream patchwork

---

hv-rhel7.x/hv/tools/bondvf.sh

To name the bondX interface, the current bondvf script just increments an integer.  I found that if you have multiple NICs and not all of them are enabled for accelerated networking, then if can be difficult to follow which bond interface is associated with which eth/vf pair.  This simple patch just names the bondX interface after the associated ethX interface.

Name bondX interface after associated ethX interface

---

hv-rhel6.x/hv/rhel6-hv-driver-install
hv-rhel6.x/hv/rhel6-hv-driver-uninstall
hv-rhel7.x/hv/Makefile

MLX4 drivers are included in 7.4 and not necessary there.

Fix some requested issues #387 and #321

---

tools/sriov/bondvf.sh
tools/sriov/configure_hv_sriov.sh

The bondvf.sh has been removed from kernel.org because of the
transparent-vf support is in place.
But some users will still use the bonding solution for Azure SRIOV
preview.
Now add the bondvf.sh to github to support that preview.

Update the SRIOV config scripts

---

tools/sriov/60-hyperv-vf-name-run.rules
tools/sriov/configure_hv_sriov.sh

In Ubuntu case, the script needs lock to write config file to
/etc/network/interfaces in the case of multiple VFs presented.
Otherwise, the config file will be in a unknown state if udev rules
trigger bondvf.sh with multiple instances and those instances will write
to the same file in the same time.

Add bondvf_lock file to support VM with multiple VFs

---

hv-rhel7.x/hv/hyperv_net.h
hv-rhel7.x/hv/netvsc.c
hv-rhel7.x/hv/netvsc_drv.c

This fixes an issue where we would reset the section size upon
tearing down and re-adding a net_device for an MTU change. If we
continuously increase the MTU, this leads to a decrease in section
count while maintaining the same section size. Since buffer size
is calculated as section_count*section_size, we eventually get a
use very small buffer size that is rejected by the host.

RH7: netvsc: Save the previous section size before reinitializing buffer

---

hv-rhel7.x/hv/channel_mgmt.c
hv-rhel7.x/hv/hv.c
hv-rhel7.x/hv/hyperv_vmbus.h
hv-rhel7.x/hv/vmbus_drv.c

1) Use notifier_block to monitor CPU hotplug events;
2) Fail the hot-unplug if this CPU is used by VMBUS channel;
3) Refine existing interface to make them fit new structures for hv_synic_* functions.
This patch referenced kernel linux-3.10.0 (693).

Add hotplug support for >Rhel 7.3

---

hv-rhel6.x/hv/hyperv_net.h
hv-rhel6.x/hv/netvsc.c
hv-rhel6.x/hv/netvsc_drv.c
hv-rhel6.x/hv/rndis_filter.c

When a virtual device is added dynamically (via host console), then
the vmbus sends an offer message for the primary channel. The processing
of this message for networking causes the network device to then
initialize the sub channels.
The problem is that setting up the sub channels needs to wait until
the subsequent subchannel offers have been processed. These offers
come in on the same ring buffer and work queue as where the primary
offer is being processed; leading to a deadlock.
This did not happen in older kernels, because the sub channel waiting
logic was broken (it wasn't really waiting).
The solution is to do the sub channel setup in its own work queue
context that is scheduled by the primary channel setup; and then
happens later.
Fixes: 732e49850c5e ("netvsc: fix race on sub …

RHEL6x: hv_netvsc: fix deadlock on hotplug

---

hv-rhel7.x/hv/channel_mgmt.c
hv-rhel7.x/hv/hv.c
hv-rhel7.x/hv/hyperv_vmbus.h
hv-rhel7.x/hv/vmbus_drv.c

The recently added code to support cpu hot-plug does not work on RHEL 7.2 and previous versions.
Add #if to those lines of code, to make it works only on RHEL7.3 and later versions.

Fix build break on RHEL 7.2

---

hv-rhel6.x/hv/tools/hv_kvp_daemon.c
hv-rhel7.x/hv/tools/hv_kvp_daemon.c

https://patchwork.kernel.org/patch/10033483/

hv: kvp: Avoid reading past allocated blocks from KVP file

---

hv-rhel6.x/hv/tools/hv_kvp_daemon.c
hv-rhel7.x/hv/tools/hv_kvp_daemon.c

https://patchwork.kernel.org/patch/10033483/

4.2.4 - hv: kvp: Avoid reading past allocated blocks from KVP file

---

.gitignore
hv-rhel5.x/hv/tools/hv_kvp_daemon.c

Backported from [hv: kvp: Avoid reading past allocated blocks from KVP file](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=297d6b6e56c2977fc504c61bbeeaa21296923f89)

RH5: backport:  hv: kvp: Avoid reading past allocated blocks from KVP file

---

hv-rhel7.x/hv/include/linux/hv_compat.h
hv-rhel7.x/hv/storvsc_drv.c

Update the algorithm in storvsc_do_io to look for a channel
starting with the current CPU + 1 and wrap around, rather
than always starting CPU #0 (within the current NUMA node
in both cases). This update spreads VMbus interrupts evenly
across CPUs instead of mostly to CPU #0.
Also update the cmd_per_lun value from 255 to 2048.  Hyper-V
can handle the larger number, and it avoids excessive CPU usage
due to blk and SCSI level requeuing when the number of
outstanding I/O's is larger then 255.

Update storvsc algorithm for selecting channel for new I/O request

---

hv-rhel7.x/hv/channel_mgmt.c
hv-rhel7.x/hv/hyperv_vmbus.h
hv-rhel7.x/hv/include/linux/hyperv.h
hv-rhel7.x/hv/vmbus_drv.c

By default, in RH7 code, vmbus will assign CPUs to channels by
considering the CPU hyper-threading.
Now, add a kernel parameter to disable it: "hv_vmbus.affinity_mode=0"

RH7: add optional vmbus parameter for HT when assigning CPU to channel

---

hv-rhel6.x/hv/ring_buffer.c
hv-rhel7.x/hv/ring_buffer.c

Rework hv_pkt_iter_close() to not use interrupt_mask to determine
whether to signal the host, and to read the ring buffer indices in
the correct order to avoid race conditions.

Rework hv_pkt_iter_close to fix missed signaling that causes hangs

---

hv-rhel7.x/hv/pci-hyperv.c

When the irqdaemon tries to set a specific affinity via the 'mask',
we should respect it, otherwise all the interrupts can go to one
CPU only.
This fixes the recent SR-IOV perf regression.
Signed-off-by: Dexuan Cui <decui@microsoft.com>

RH7: PCI: hv: respect the affinity setting

---

hv-rhel7.x/hv/tools/systemd/hv_fcopy_daemon.service

When guest services aren't enabled, systemd cannot launch the fcopy service and systemctl status shows a degraded system state.
This patch allows the hv_fcopy_daemon not to make systemctl state degraded anymore.

Improve hv_fcopy_daemon unit file

---

hv-rhel6.x/hv/Makefile
hv-rhel6.x/hv/arch/x86/hyperv/hv_init.c
hv-rhel6.x/hv/arch/x86/hyperv/ms_hyperv_ext.c
hv-rhel6.x/hv/arch/x86/include/lis/asm/mshyperv.h
hv-rhel6.x/hv/hv.c
hv-rhel6.x/hv/vmbus_drv.c
hv-rhel7.x/hv/hv.c

This PR fixes a VM boot-time hang issue on some RS4 hosts, where ms_hyperv_ext.hints.bit9(HV_X64_DEPRECATING_AEOI_RECOMMENDED) = 1.

For the 4.2.5 branch: Fix VM boot-time hang issues for RHEL 6.x and 7.x on a RS4 host

---

hv-rhel6.x/hv/Makefile
hv-rhel6.x/hv/arch/x86/hyperv/hv_init.c
hv-rhel6.x/hv/arch/x86/hyperv/ms_hyperv_ext.c
hv-rhel6.x/hv/arch/x86/include/lis/asm/mshyperv.h
hv-rhel6.x/hv/hv.c
hv-rhel6.x/hv/vmbus_drv.c
hv-rhel7.x/hv/hv.c

This PR fixes a VM boot-time hang issue on some RS4 hosts, where ms_hyperv_ext.hints.bit9(HV_X64_DEPRECATING_AEOI_RECOMMENDED) = 1.

For master branch: Fix VM boot-time hang issues for RHEL 6.x and 7.x on a RS4 host

---

hv-rhel7.x/hv/netvsc_compat.h

lis-next fails to build on 7.3 and older 7.x, fixing 2 different issues.

 netvsc_compat fix for rhel <7.3

---

hv-rhel7.x/hv/provider.c

RHEL 7.5 moved to a newer mechanism for registering device and setup DMA masks.
Add support for RHEL 7.5.

Support RHEL 7.5 RDMA device registration

---

hv-rhel7.x/hv/netvsc_compat.h

fix: a10d539cd1a0421f596d590e18bfc2b9fbdca1c1
netvsc: introduce compat.h to workaround kernel API changes
Signed-off-by: Haiyang Zhang <haiyangz@microsoft.com>

RH7: fix compat layer of __napi_schedule_irqoff()

---

hv-rhel7.x/hv/netvsc.c

If out ring is full temporarily and receive completion cannot go out,
we may still need to reschedule napi if certain conditions are met.
Otherwise the napi poll might be stopped forever, and cause network
disconnect.
Fixes: 7426b1a51803 ("netvsc: optimize receive completions")
Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>
Signed-off-by: Haiyang Zhang <haiyangz@microsoft.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

RH7: hv_netvsc: Fix napi reschedule while receive completion is busy

---

hv-rhel7.x/hv/channel.c
hv-rhel7.x/hv/channel_mgmt.c
hv-rhel7.x/hv/include/linux/hyperv.h

slow_virt_to_phys() is only implemented for arch/x86.
Remove its use in arch independent Hyper-V drivers, and
replace with test for vmalloc() address followed by
appropriate v-to-p function. This follows the typical
pattern of other drivers and avoids the need to implement
slow_virt_to_phys() for Hyper-V on ARM64.

RH7:Drivers: hv: vmbus: Remove use of slow_virt_to_phys()

---

hv-rhel7.x/hv/hv.c

changed cleanup synic memory free path for centos7.x and tested it in centos7.5, and centos7.0

rh7:vmbus:cleanup synic memory free path

---

hv-rhel7.x/hv/netvsc_drv.c

Cherry-picked from lis-next/master: 25c11bb2334036816cb94e643013ba314cbed4eb

RH7: hv_netvsc: Fix a network regression after ifdown/ifup

---

hv-rhel7.x/hv/netvsc_drv.c

Fix the "No IP address via DHCP" issue when AN is enabled.
Cherry-picked from lis-next/master: 97edf12835fa176a9c61278d49e401e272b02ec6

RH7:hv_netvsc:set master device

---

hv-rhel7.x/hv/netvsc.c
hv-rhel7.x/hv/netvsc_drv.c
hv-rhel7.x/hv/pci-hyperv.c

1.PCI: hv: support reporting serial number as slot information
2.hv_netvsc: pair VF based on serial number
3.hv_netvsc: fix vf serial matching with pci slot info

 RH7 : code changes for the below PCI patches.

---

hv-rhel6.x/hv/vmbus_drv.c

The Fix used to resolve the compiling error for Centos 6.0,6.1,6.2, 6.3 and 6.4

RH6.x: Resolving the VMBUS kfree_rcu build error for RH <= 6.4

---

hv-rhel7.x/hv/arch/x86/hyperv/hv_init.c

Otherwise unbind fails with error "No such device".
Max size set as:
#define CS_NAME_LEN       32
In kernel file:
linux-3.10.0-693.43.1.el7/kernel/time/tick-internal.h

RH7: Shorten clocksource name to less than 32 chars

---

hv-rhel6.x/hv/netvsc_drv.c

This fixes ifconfig statistics issue seen in RH6x after implementing transparent sriov.
Code added to increment master synthetic interface stats for stats increment of slave VF interface.
This will make behavior similar to what we seen RH7x.

RH6: netvsc: Increament master if stats with slave VF if stats

---

hv-rhel6.x/hv/hyperv_net.h
hv-rhel6.x/hv/netvsc_drv.c

Backport of RH7 commit: 673694263aa999e55500ab57ad4621646b6bb69a
This fixes warning "function netvsc_inject_enable defined but not used".

RH6: hv_netvsc: remove VF in flight counters

---

hv-rhel6.x/hv/ring_buffer.c

When hv_netvsc module is unloaded using modprobe and lsvmbus utility is executed, a crash was observed. Now the issue is fixed.

Fix for bug 20102263 - Crash was observed in RH6.X

---

hv-rhel6.x/hv/pci-hyperv.c

The unused variable is deleted and type cast is done to remove the build
warning for pci-hyperv

RH6: Removing build warning for pci-hyperv

---

hv-rhel6.x/hv/arch/x86/include/uapi/lis/asm/hyperv.h
hv-rhel6.x/hv/pci-hyperv.c

This is backport of these RH7 commits:
16370f95df2890bf2ef884b970f3d58558312b2e
679cd43cbddd6d63f1ba001a055be6f78cc74b79
fe4bfc622be20380da0da02c81568a582304a512

RH6: Add support for PCI protocol version 1.2

---

hv-rhel6.x/hv/channel_mgmt.c
hv-rhel6.x/hv/connection.c
hv-rhel6.x/hv/hyperv_vmbus.h
hv-rhel6.x/hv/include/linux/hyperv.h
hv-rhel6.x/hv/vmbus_drv.c

@santoshx @prashantmhetar @mboitei 
This changes required to be merged separately. Dont squash merge.

RH6: Revert all changes made for: hv:vmbus:Remove the useless API vmbus_get_outgoing_channel

---

hv-rhel6.x/hv/netvsc_drv.c

Backported from RH7. SHA: 25c11bb2334036816cb94e643013ba314cbed4eb

RH6: hv_netvsc: Fix a network regression after ifdown/ifup

---

hv-rhel6.x/hv/channel_mgmt.c
hv-rhel6.x/hv/include/linux/hyperv.h

Backported from RH7: SHA: ca51a433ee97bb03a9cfdb72cd826a9529c4196a

RH6: hv: vmbus: Remove the useless API vmbus_get_outgoing_channel()

---

hv-rhel6.x/hv/hyperv_net.h
hv-rhel6.x/hv/netvsc_drv.c

Backported from RH7. SHA: b41831531ae57d28e7114056cbced5e34f94f5a2
On top of backport new modification was added to support the device name
allocation as it was done in register_netdev() in RH6 kernel

RH6: hv_netvsc: fix network namespace issues with VF support

---

hv-rhel6.x/hv/pci-hyperv.c

Below patches are back-ported from RH7 to resolve the VF rescind issues.
It has been tested for CentOS 6.7, 6.8, 6.9 and 6.10 with MLNX_OFED_LINUX-4.4-2.0.7.0 by enabling/disabling the SRIOV setting

Fix and back-port the patches for LIS 4.3: Transparent SRIOV in RHEL 6.x: fix the bug in VF rescind

---

hv-rhel6.x/hv/pci-hyperv.c

Backported from RH7: SHA:16edc0c054b6f8f8d298847739ea06bca604b1d3

RH6: PCI: hv: Fix wslot_to_devfn() to fix warnings on device removal

---

hv-rhel6.x/hv/netvsc_drv.c

Backported from RH7: SHA: 577f6baf9d5d1cd3bc77e42237d0268cd6aeb982
Additional changes was done to remove the netvsc_vf_down() invoking
from netvsc_unregister_vf().

RH6: netvsc: cleanup datapath switch

---

hv-rhel6.x/hv/netvsc_drv.c

This is just to simplify code and moreover netdev_extended
is not available in < RH67.

RH6: Use master instead of rx_handler_data

---

hv-rhel6.x/hv/netvsc_drv.c

This prevents a crash that occurs during hot enable of SRIOV while ntttcp test is ongoing.

RH6: Handle congestion notification from dev_queue_xmit

---

hv-rhel7.x/hv/netvsc_drv.c

Backported from: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=018349d70f28a78d5343b3660cb66e1667005f8a

RH7: hv_netvsc: fix schedule in RCU context

---

hv-rhel7.x/hv/tools/hv_fcopy_daemon.c

This is backport of upstream commit:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=c2d68afba86d1ff01e7300c68bc16a9234dcd8e9

RH7: hv_fcopy: set 'error' in case an unknown operation was requested

---

hv-rhel6.x/hv/netvsc_drv.c

This prevents a general protection fault crash seen during ntttcp udp test.

RH6: Handle negative returns from dev_queue_xmit

---

hv-rhel7.x/hv/uio_hv_generic.c

This is backport of upstream commit:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=108ddb8fa1fc310be4a6bd1e308bca62821ee8b5&context=10&ignorews=0&dt=0

RH7: uio_hv_generic: increase size of receive and send buffers

---

hv-rhel7.x/hv/pci-hyperv.c

Backported from: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=54be5b8ce33f8d1a05b258070c81ed98f935883d

RH7: PCI: hv: Fix return value check in hv_pci_assign_slots

---

hv-rhel6.x/hv/rndis_filter.c

Backported from RH7: SHA: cfd9ff2ab58d8c93171fd3e9a73477300c08ddd1

RH6: hv_netvsc: Set tx_table to equal weight after subchannels open

---

hv-rhel7.x/hv/channel.c
hv-rhel7.x/hv/channel_mgmt.c
hv-rhel7.x/hv/include/linux/hyperv.h
hv-rhel7.x/hv/vmbus_drv.c

Backporting from https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=800b932969c53c4044ff9f9fd1ee793a87fa8ef0

RH7: vmbus: pass channel to hv_process_channel_removal

---

hv-rhel7.x/hv/hv.c
hv-rhel7.x/hv/include/linux/hyperv.h
hv-rhel7.x/hv/vmbus_drv.c

1. RH7: vmbus: add driver_override support
2. RH7: hv: vmbus: Fix synic per-cpu context initialization

RH7: Vmbus backport from upstream

---

hv-rhel7.x/hv/pci-hyperv.c

This reverts commit 636fd886122a020abc0f715d41befb5fc8c32ed4.
(cherry picked from commit c4e45f46e93f1b5bd99bcef447883437da23b422)

Revert "RH7: PCI: hv: Make sure the bus domain is really unique"

---

hv-rhel7.x/hv/channel.c
hv-rhel7.x/hv/include/linux/hyperv.h
hv-rhel7.x/hv/ring_buffer.c

Backported from: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=ae6935ed7d424ffa74d634da00767e7b03c98fd3
Removed setting 'num_sc' as it has been deleted from 'struct vmbus_channel' in patch sha: ca51a433ee97bb03a9cfdb72cd826a9529c4196a

RH7: vmbus: split ring buffer allocation from open

---

hv-rhel7.x/hv/connection.c

This is backport of upstream commit:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=41e270f6898e7502be9fd6920ee0a108ca259d36

RH7: Drivers: hv: vmbus: Use get/put_cpu() in vmbus_connect()

---

hv-rhel7.x/hv/hv_kvp.c

Backporting from: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=16d1342bc41ad417812f8a800a1799b5d1c026dc

RH7: hv: kvp: Use %u to print U32

---

hv-rhel7.x/hv/hv_util.c

Backporting from: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=5c24ee897664822956b1830df6957bb7f8965bb3

RH7: hv_utils: update name in struct hv_driver util_drv

---

hv-rhel7.x/hv/hv.c
hv-rhel7.x/hv/hyperv_vmbus.h

Backport of upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=a3cadf3850cd901a11b8ec610ac627ecbe3a87a5

RH7: Drivers: hv: vmbus: Get rid of unnecessary state in hv_context

---

hv-rhel7.x/hv/hid-hyperv.c
hv-rhel7.x/hv/hyperv-keyboard.c

This is a backport of upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=10f91c73cc41ceead210a905dbd196398e99c7d2

RH7: Input: hyper-v - fix wakeup from suspend-to-idle

---

hv-rhel7.x/hv/netvsc_drv.c

This is backport of upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=98ba780e4c71b9a66fa5819184879315a946aabb

RH7: net/hyperv: use skb_vlan_tag_*() helpers

---

hv-rhel7.x/hv/tools/hv_kvp_daemon.c

This is a backport of upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=4fcba7802c3e15a6e56e255871d6c72f829b9dd8

RH7: Tools: hv: kvp: Fix a warning of buffer overflow with gcc 8.0.1

---

hv-rhel7.x/hv/vmbus_drv.c

Backporting from: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=fc96df16a1ce80cbb3c316ab7d4dc8cd5c2852ce

RH7: hv: vmbus: Return -EINVAL for the sys files for unopened channels

---

hv-rhel7.x/hv/netvsc_drv.c

This resolves the 'napi' unused-variable warning for <= 7.1 distros

Fix for warning in netvsc_alloc_recv_skb

---

hv-rhel7.x/hv/hyperv_net.h
hv-rhel7.x/hv/netvsc.c
hv-rhel7.x/hv/netvsc_drv.c

Backported from upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=52d3b4949192e93b948daaa40678fcd4b94bcbd0

RH7: hv_netvsc: fix typos in code comments

---

hv-rhel7.x/hv/channel_mgmt.c
hv-rhel7.x/hv/hyperv_vmbus.h
hv-rhel7.x/hv/vmbus_drv.c

RH7: Drivers: hv: vmbus: Expose monitor data only when monitor pages are used
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=next-20190508&id=46fc15487d02451448c11b83c4d086d87a6ad588

Task #21536830: LIS-4.3.2: Driver: hv vmbus: driver backport (3rd & 4th of 5)

---

hv-rhel7.x/hv/channel_mgmt.c
hv-rhel7.x/hv/hyperv_vmbus.h
hv-rhel7.x/hv/include/linux/hyperv.h
hv-rhel7.x/hv/ring_buffer.c
hv-rhel7.x/hv/vmbus_drv.c

This reverts commit e792e801d3b72a16bb80b6aef50c333d71c78c52.
Revert because it cause a crash.

Revert "RH7: Drivers: hv: vmbus: Fix race condition with new ring_buffer_info mutex"

---

hv-rhel7.x/hv/pci-hyperv.c

In the case of cpumask_equal(mask, cpu_online_mask) == false, "mask" may
be a superset of "cfg->domain", and the real affinity is still saved in
"cfg->domain", after __ioapic_set_affinity() returns. See the line
"cpumask_copy(cfg->domain, tmp_mask);" in RHEL 7.x's kernel function
__assign_irq_vector().
So we should always use "cfg->domain", otherwise the NVMe driver may
fail to receive the expected interrupt, and later the buggy error
handling code in nvme_dev_disable() can cause the below panic:
[   71.695565] nvme nvme7: I/O 19 QID 0 timeout, disable controller
[   71.724221] ------------[ cut here ]------------
[   71.725067] WARNING: CPU: 4 PID: 11317 at kernel/irq/manage.c:1348 __free_irq+0xb3/0x280
[   71.725067] Trying to free already-free IRQ 226
[   71.725067] Modules linked in: …

RH7: PCI: hv: Fix the affinity setting for the NVMe crash

---

hv-rhel7.x/hv/pci-hyperv.c

Backported from upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=01e7d61b8ace0835ff608dece4fdd87f8a29b7d3

RH7: PCI: hv: Detect and fix Hyper-V PCI domain number collision

---

hv-rhel7.x/hv/storvsc_drv.c

Backported from upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=adfbd028e155fca3bbe33d458f2f27cb657e5792
This commit is different from original backport because scsi_change_queue_depth
() is not supported in older kernel. We need to use scsi_adjust_queue_depth()
to support queue depth change in older kernel (for RH/CentOS).

RH7: scsi: storvsc: Add ability to change scsi queue depth

---

hv-rhel7.x/hv/include/linux/hyperv.h
hv-rhel7.x/hv/netvsc.c
hv-rhel7.x/hv/netvsc_drv.c
hv-rhel7.x/hv/ring_buffer.c

Fixes: 553354267fa (RH7: scsi: netvsc: Use the vmbus function to calculate ring buffer percentage (corrected for 7.0|7.x))

RH7: netvsc: Modify hv_get_avail_to_write_percent to support older kernel

---

hv-rhel7.x/hv/hyperv_net.h
hv-rhel7.x/hv/netvsc.c

Back-porting below patches from upstream:
1. https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=71f21959dd5516031db4f011e15e9a9508b93a7d
2. https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/net/hyperv?id=171c1fd98df3d5948d9a9eb755274850fa5e59c6

RH7: Backporting netvsc changes from upstream

---

hv-rhel6.x/hv/rhel6-hv-driver-install

Do this because:
hv-rhel6.x/hv/tools/hv_kvp_daemon.c:#define KVP_SCRIPTS_PATH "/usr/libexec/hypervkvpd/"

Install IP injection scripts to /usr/libexec/hypervkvpd
