LIS/lis-next

- hv-rhel5.x/hv/channel.c
- hv-rhel6.x/hv/channel.c
- hv-rhel7.x/hv/channel.c
- hv-rhel7.x/hv/include/linux/hyperv.h
All the changes related to vmbus are in this pull request.
> Merging changes from upstream

- hv-rhel7.x/hv/channel.c
- hv-rhel7.x/hv/channel_mgmt.c
- hv-rhel7.x/hv/include/linux/hyperv.h
back porting kys 3 NUMA related patches to rh7 tree.
> Back porting  NUMA related patch's.

- hv-rhel5.x/hv/include/linux/hv_compat.h
To support mouse on RHEL5.2-5.4
> Redefine WARN_ON for hid_core.c

- hv-rhel7.x/hv/netvsc_drv.c
1. Reorg netvsc feature flags.
Migrated from upstream patch
a060679c6b3da17dc9e95d0500f811de118ec901
2. Continue using
netvsc_set_hash() with Toeplitz hash.
> hv_netvsc: fix netvsc performance regression

- hv-rhel5.x/hv/netvsc_drv.c
- hv-rhel6.x/hv/netvsc_drv.c
> Revert "Use upstream Jenkins hash for RSS hashing in rhel7.x driver"

- hv-rhel5.x/hv/netvsc_drv.c
- hv-rhel6.x/hv/netvsc_drv.c
> Revert "Revert "Use upstream Jenkins hash for RSS hashing in rhel7.x driver""

- hv-rhel6.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/netvsc_drv.c
upstream commit ID cb2911fed61497e4d0383355f1c865fcdaa94061
> hv_netvsc: Fix VF register on vlan devices

- hv-rhel6.x/hv/hyperv_net.h
- hv-rhel6.x/hv/netvsc.c
- hv-rhel6.x/hv/netvsc_drv.c
- hv-rhel6.x/hv/rndis_filter.c
- hv-rhel6.x/hv/storvsc_drv.c
- hv-rhel6.x/hv/tools/bondvf.sh
- hv-rhel6.x/hv/vmbus_drv.c
Restoring the previous reverted patches.
> Revert "Revert "RH6 series of patches""

- hv-rhel7.x/hv/channel_mgmt.c
- hv-rhel7.x/hv/connection.c
- hv-rhel7.x/hv/hv.c
- hv-rhel7.x/hv/hyperv_vmbus.h
- hv-rhel7.x/hv/include/linux/hv_compat.h
- hv-rhel7.x/hv/vmbus_drv.c
> Revert "rh7: vmbus: put related per-cpu variable together"

- hv-rhel6.x/hv/netvsc.c
- hv-rhel6.x/hv/netvsc_drv.c
This is a RHEL6.x only fix. No need for RHEL7.x tree.
> [hv-rhel6.x] include the per-channel stats for reporting

- hv-rhel6.x/hv/netvsc_drv.c
> RH6: hv: fix rx-checksumming support

- hv-rhel6.x/hv/channel_mgmt.c
- hv-rhel7.x/hv/channel_mgmt.c
- hv-rhel7.x/hv/storvsc_drv.c
Backport of DVD device SCSI version fix from upstream.
Backport of tasklet schedule form stable submission.
> Fixes for boot hang on Rhel7 and ported to RH6 as well.

- hv-rhel7.x/hv/netvsc_drv.c
This patch reverts the change of
77f8efca95217b4fdf512b7f38532ae358a55db6 (committed on Feb 13, 2017).
> Use Toeplitz Hash in netvsc netvsc_select_queue()

- tools/hyperv_kdump_config.ps1
- tools/kdump_configure.sh
Added scripts for kdump configuration for Linux VMs running on Hyper-V hosts.
> Kdump Hyper-V Linux VM config scripts

- hv-rhel6.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/netvsc_drv.c
40975962788ef5b796ab0f36bfd7051064c915d3
Don't need need to look at write space in netvsc_close.
> netvsc: use hv_get_bytes_to_read

- hv-rhel6.x/hv/hyperv_net.h
- hv-rhel6.x/hv/include/linux/hv_compat.h
- hv-rhel6.x/hv/rndis_filter.c
- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/include/linux/hv_compat.h
- hv-rhel7.x/hv/rndis_filter.c
> netvsc: use refcount_t for keeping track of sub channels

- hv-rhel5.x/hv/channel.c
- hv-rhel5.x/hv/netvsc.c
- hv-rhel5.x/hv/rndis_filter.c
Get rid of completion timeouts on RH5.
This is to address issue #403
> RH5: get rid of completion timeouts

- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/netvsc.c
- hv-rhel7.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/rndis_filter.c
- hv-rhel7.x/hv/tools/bondvf.sh
The main commit is bringing the transparent VF management changes over to 4.2.3.
> Merge master into 4.2.3

- hv-rhel6.x/hv/channel.c
- hv-rhel6.x/hv/channel_mgmt.c
- hv-rhel6.x/hv/hv_balloon.c
- hv-rhel6.x/hv/hv_kvp.c
- hv-rhel6.x/hv/include/linux/hv_compat.h
- hv-rhel6.x/hv/include/linux/hyperv.h
- hv-rhel6.x/hv/tools/hv_fcopy_daemon.c
- hv-rhel6.x/hv/tools/hv_kvp_daemon.c
- hv-rhel6.x/hv/vmbus_drv.c
- hv-rhel7.x/hv/channel.c
- hv-rhel7.x/hv/hv_balloon.c
- hv-rhel7.x/hv/hv_kvp.c
- hv-rhel7.x/hv/include/linux/hyperv.h
- hv-rhel7.x/hv/tools/hv_fcopy_daemon.c
- hv-rhel7.x/hv/tools/hv_kvp_daemon.c
7b6e54b524b66b60e4cf49e8aa7c43045ebb987d
Previously we were only showing max number of pages. We should make it
more clear that this value is the max amount of dynamic memory that the
Hyper-V host is willing to assign to this guest.
> upstream backports

- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/rndis_filter.c
Cherry-pick patches from master branch that are required to fix this issue.
> Fix the NIC hot-add hangs in Gen2 VMs

- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/rndis_filter.c
Fix issue with NIC hot-adds stalling
> RH7: [PATCH] netvsc: defer initializing sub-channels

- hv-rhel7.x/hv/vmbus_rdma.h
RHEL 7.3 moved to new IDR interfaces, using old IDR functions may return some results that RDMA driver doesn't expect.
Also replace BUG_ON with WARN, because we should not panic kernel on IDR errors.
> Move to newer IDR functions for RHEL 7.3 or above

- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/netvsc.c
- hv-rhel7.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/rndis_filter.c
… <upstream:6b0cbe315868d613123cf387052ccda5f09d49ea>
> netvsc upstream backports for RH7

- hv-rhel7.x/hv/pci-hyperv.c
Upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/helgaas/pci.git/commit/?h=pci/host-hv&id=79aa801e899417a56863d6713f76c4e108856000
PCI: hv: Use effective affinity maskpci/host-hv
The effective_affinity_mask is always set when an interrupt is assigned
in
__assign_irq_vector() -> apic->cpu_mask_to_apicid(), e.g. for struct
apic
apic_physflat: -> default_cpu_mask_to_apicid() ->
irq_data_update_effective_affinity(), but it looks d->common->affinity
remains all-1's before the user space or the kernel changes it later.
In the early allocation/initialization phase of an IRQ, we should use
the
effective_affinity_mask, otherwise Hyper-V may not deliver the interrupt
to
the expected CPU.  Without the patch, if we assign 7 Mellanox ConnectX-3
VFs to a 32-vCPU VM, one of the VFs may fail to …
> RH7: PCI: hv: Use effective affinity mask

- hv-rhel6.x/hv/channel.c
- hv-rhel6.x/hv/channel_mgmt.c
- hv-rhel6.x/hv/include/linux/hyperv.h
https://patchwork.kernel.org/patch/10057685/
> RH6: Drivers: hv: vmbus: Fix a rescind issue

- hv-rhel5.x/hv/include/linux/hv_compat.h
- hv-rhel6.x/hv/include/linux/hv_compat.h
- hv-rhel7.x/hv/include/linux/hv_compat.h
> LIS 4.2.4 Beta2 update tag

- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/netvsc.c
- hv-rhel7.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/rndis_filter.c
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=a7f99d0f2bbfe3b42ce398cdd37a97762e72cb56
> RH7: hv_netvsc: use reciprocal divide to speed up percent calculation

- hv-rhel7.x/hv/netvsc_drv.c
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=f5a2255010b0bde6df5a9060dbc826ad14ad4c44
> RH7: hv_netvsc: optimize initialization of RNDIS header

- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/netvsc.c
- hv-rhel7.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/rndis_filter.c
@chvalean -- Please take a look at netvsc.c:727 Re: [Checkin#333](https://github.com/LIS/lis-next/commit/29dfeae83e466afcfac54486ffcdcef6d79cf688)
> RH7: Hv_netvsc: empty current transmit aggregation if flow blocked

- hv-rhel5.x/hv/include/linux/hv_compat.h
- hv-rhel6.x/hv/include/linux/hv_compat.h
- hv-rhel7.x/hv/include/linux/hv_compat.h
> LIS 4.2.4-beta5

- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/netvsc.c
- hv-rhel7.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/rndis_filter.c
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=cfd8afd986cdb59ea9adac873c5082498a1eb7c0
> RH7: Hv netvsc empty current transmit aggregation if flow blocked

- hv-rhel6.x/hv/uio_hv_generic.c
- hv-rhel7.x/hv/uio_hv_generic.c
RH6/7: uio_hv_generic: create send and receive buffers
RH6/7: uio_hv_generic: check that host supports monitor page 
RH6/7: uio_hv_generic: add rescind support
> RH6/7: uio_hv_generic: create send and receive buffers, check that host supports monitor page, add rescind support

- hv-rhel6.x/hv/uio_hv_generic.c
- hv-rhel7.x/hv/uio_hv_generic.c
RH6: uio_hv_generic: create send and receive buffers  …
RH7: uio_hv_generic: create send and receive buffers  …
RH6: uio_hv_generic: check that host supports monitor page  …
RH7: uio_hv_generic: check that host supports monitor page  …
RH7: uio_hv_generic: add rescind support  …
RH6: uio_hv_generic: add rescind support
> uio_hv_generic: create send and receive buffers, check that host supports monitor page, add rescind support

- hv-rhel6.x/hv/hv_balloon.c
- hv-rhel7.x/hv/hv_balloon.c
* hv_balloon: fix printk loglevel
* hv_balloon: simplify hv_online_page()/hv_page_online_one()
* hv_balloon: fix bugs in num_pages_onlined accounting
> hv_balloon backports (#521)

- hv-rhel6.x/hv/hyperv_net.h
- hv-rhel6.x/hv/netvsc.c
- hv-rhel6.x/hv/rndis_filter.c
- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/netvsc.c
- hv-rhel7.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/rndis_filter.c
Merged the patch 30 as part of lis-next repository. Please review
> hv-netvsc: simplify receive side calling arguments

- hv-rhel7.x/hv/include/linux/hv_compat.h
- hv-rhel7.x/hv/uio_hv_generic.c
modifed ring buffer attribute in uio_hv_generic.c and validated it in centos7.0, centos7.4, and centos7.5
> RH7:uio_hyperv:modify ring buffer attribute

- hv-rhel7.x/hv/connection.c
- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/hyperv_vmbus.h
- hv-rhel7.x/hv/include/linux/hyperv.h
- hv-rhel7.x/hv/netvsc.c
- hv-rhel7.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/rndis_filter.c
- hv-rhel7.x/hv/tools/hv_vss_daemon.c
- hv-rhel7.x/hv/tools/lsvmbus
RH7:hv:vmbus: Enable VMBus protocol version 5.0
>  RH7:hv:vmbus: Enable VMBus protocol version 5.0

- hv-rhel7.x/hv/netvsc_drv.c
hv_netvsc: Add handlers for ethtool get/set msg level.
> RH7:hv_netvsc: Add handlers for ethtool get/set msg level

- hv-rhel6.x/hv/include/linux/hyperv.h
- hv-rhel6.x/hv/ring_buffer.c
- hv-rhel7.x/hv/include/linux/hyperv.h
- hv-rhel7.x/hv/ring_buffer.c
updated comments of ring buffer in RH6, RH7 and verified them
> RH6,RH7:ring_buffer.c,hyperv.h:changed comments of ring buffer

- hv-rhel7.x/hv/arch/x86/include/lis/asm/mshyperv.h
- hv-rhel7.x/hv/hv.c
changed timer and interrupt macros in mshyperv.h and hv.c for cent7.x and the tests were passed
> rh7:hv.c:changed timer, interrput macros

- hv-rhel5.x/hv/rhel5-hv-driver-install
- hv-rhel5.x/hv/rhel5-hv-driver-uninstall
- hv-rhel6.x/hv/Makefile
- hv-rhel6.x/hv/rhel6-hv-driver-install
- hv-rhel6.x/hv/rhel6-hv-driver-uninstall
- hv-rhel7.x/hv/Makefile
- hv-rhel7.x/hv/rhel7-hv-driver-install
- hv-rhel7.x/hv/rhel7-hv-driver-uninstall
Redoing PR https://github.com/LIS/lis-next/pull/427 since it seems to have lost where I originated from, and being an open PR for about a year, things got out of date.
> allow building against an installed, but non-running kernel

- hv-rhel7.x/hv/hyperv_net.h
- hv-rhel7.x/hv/netvsc.c
- hv-rhel7.x/hv/netvsc_drv.c
- hv-rhel7.x/hv/rndis_filter.c
This is only a tempoary workaround.
We may need to drop this patch in future.
Signed-off-by: Dexuan Cui <decui@microsoft.com>
> hv_netvsc: Fix a deadlock issue in the case of multiple NICs

- hv-rhel6.x/hv/hyperv_bond_3ad.h
- hv-rhel6.x/hv/hyperv_bond_alb.h
- hv-rhel6.x/hv/hyperv_bond_options.h
- hv-rhel6.x/hv/hyperv_bonding.h
- hv-rhel6.x/hv/netvsc_drv.c
fixed the compiling error in redhat6.7, and tested the patch in redhat6.7, 6.8, 6.10. They are all correct.
> fixed compiling error in redhat6.7 using transparent sriov patch

- hv-rhel6.x/hv/netvsc_drv.c
This patch is tested for 6.4, 6.7, 6.9 and 6.10 RHEL Distros for install/uninstall build
> RH6: To resolve the Build error for < 6.7

- hv-rhel6.x/hv/pci-hyperv.c
Also did some indentation & spaceing fix
> RH6: pci-hyperv.c: Fix compile warning in hook_func

- hv-rhel6.x/hv/hyperv_net.h
- hv-rhel6.x/hv/netvsc.c
- hv-rhel6.x/hv/netvsc_drv.c
- hv-rhel6.x/hv/rndis_filter.c
Backported from RH7. SHA: 7d3bdcb3a2a05b4f3fed8ef70851b097136abdf6.
> RH6: Drivers: hv_netvsc: common detach logic

- hv-rhel6.x/hv/hyperv_net.h
- hv-rhel6.x/hv/netvsc.c
- hv-rhel6.x/hv/netvsc_drv.c
- hv-rhel6.x/hv/rndis_filter.c
Backported from RH7: SHA: 673f5302723eacc3b9172e6ab25927bc59b75269
> RH6: hv_netvsc: split sub-channel setup into async and sync

- hv-rhel6.x/hv/netvsc_drv.c
This fixes various random kernel crashes seen.
> RH6: Add netif_queue_stopped check for VF xmit

- hv-rhel6.x/hv/netvsc_drv.c
We dont need everything that is done in netdev_set_master().
We define netvsc_set_master() to do just what we need.
This prevents a crash that occurs in ib_core module during
hot enable of sriov in hyperv settings.
> RH6: Fix crash during hot enable of sriov from hyperv settings

- hv-rhel6.x/hv/netvsc_drv.c
Data transmission from VF txq will cause packet drop when queue is stopped
or frozen. In such case sythetic datapath should be used to continue tx.
This patch also improves the performance when the number of connection
increases.
> RH6: hv_netvsc: Fix for packet drop during xmit from VF

- hv-rhel7.x/hv/netvsc_drv.c
This is backport of upstream commit:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=2a7f8c3b1d3feedee3aa319ac220cbde3725b5d5
> RH7: hv_netvsc: remove ndo_poll_controller

- hv-rhel7.x/hv/channel.c
- hv-rhel7.x/hv/channel_mgmt.c
Backporting from : https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=fe857bb40fb6788afe6b12b1df50b94e2d363c89
> RH7: hv: vmbus: Fix the descriptions of some function parameters

- hv-rhel6.x/hv/netvsc_drv.c
Refactored netvsc_txq_stopped_or_frozen to seperate queue
computation and assignment and queue status checking.
> RH6: hv_netvsc: Refactor netvsc_txq_stopped_or_frozen

- hv-rhel7.x/hv/pci-hyperv.c
This reverts commit 636fd886122a020abc0f715d41befb5fc8c32ed4.
> Revert "RH7: PCI: hv: Make sure the bus domain is really unique"

- hv-rhel7.x/hv/hv_kvp.c
Backporting from : https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=fc62c3b1977d62e6374fd6e28d371bb42dfa5c9d
> RH7: hv: kvp: Fix two "this statement may fall through" warnings

- hv-rhel7.x/hv/channel_mgmt.c
Backport from upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=25355252607ca288f329ee033f387764883393f6
> RH7: Drivers: hv: vmbus: Use cpumask_var_t for on-stack cpu mask

- hv-rhel7.x/hv/include/linux/hv_compat.h
- hv-rhel7.x/hv/netvsc_drv.c
Backport of upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=98ba780e4c71b9a66fa5819184879315a946aabb
> TASK # 21349051: RH7: net/hyperv: use skb_vlan_tag_*() helpers

- hv-rhel7.x/hv/include/linux/hyperv.h
- hv-rhel7.x/hv/ring_buffer.c
- hv-rhel7.x/hv/vmbus_drv.c
…itions
Backport of upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=next-20190508&id=396ae57ef1ef978d1d21cdb7586ba184a3f22453
> Task #21536830: LIS-4.3.2: Driver: hv vmbus: driver backport (2 of 5)

- hv-rhel7.x/hv/channel_mgmt.c
- hv-rhel7.x/hv/hyperv_vmbus.h
- hv-rhel7.x/hv/include/linux/hyperv.h
- hv-rhel7.x/hv/ring_buffer.c
- hv-rhel7.x/hv/vmbus_drv.c
Backport of upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=next-20190508&id=14948e39445db674516ccabdf01090586ecfdc9b
> Task #21536830: LIS-4.3.2: Driver: hv vmbus: driver backport (5th of 5)

- hv-rhel7.x/hv/storvsc_drv.c
> RH7: storvsc upstream backport

- hv-rhel7.x/hv/storvsc_drv.c
> Revert "RH7: storvsc upstream backport"

- hv-rhel6.x/hv/include/linux/hv_compat.h
- hv-rhel6.x/hv/storvsc_drv.c
> Revert "Storvsc backports"
